// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // In Prisma v7, the CLI uses the `url` defined here (which replaces the old `directUrl` functionality). 
    // Your actual runtime application relies on `DATABASE_URL` via the pg adapter in `lib/db.ts`.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
}); 0
