import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Oxanium, Share_Tech_Mono, Syncopate } from "next/font/google";
import "./globals.css";
import { BalanceProvider } from "@/lib/context/BalanceContext";

const primaryFont = Oxanium({
  variable: "--font-sans",
  subsets: ["latin"],
});

const monoFont = Share_Tech_Mono({
  weight: "400",
  variable: "--font-mono",
  subsets: ["latin"],
});

const displayFont = Syncopate({
  weight: ["400", "700"],
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${monoFont.variable} ${displayFont.variable} antialiased`}
      >
        <BalanceProvider>
          <Navbar />
          {children}
        </BalanceProvider>
      </body>
    </html>
  );
}
